trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/customers/urls.py
from django.urls import path
from . import views


app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('registration/', views.registration, name="registration"),
    path('detail/<int:user_id>', views.detail, name="detail"),
    path('change/<int:user_id>/', views.change, name="change"),
    path('pickup/<int:user_id>/', views.pickup, name="pickup"),
    path('suspension/<int:user_id>/', views.suspension, name="suspension"),
    path('statement/<int:user_id>/', views.statement, name="statement")
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('registration/', views.registration, name='registration'),
    path('route/', views.daily_view, name='route'),
    path('confirmation/', views.confirm_pickup, name='confirmation'),

]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding django's built in routes (login and logout). Notice there is no login function in accounts/views.py
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/lux/bootstrap.min.css" integrity="sha384-9+PGKSqjRdkeAU7Eu4nkJU8RFaH8ace8HGXnkiKMP9I9Te0GJ4/km3L1Z8tXigpG" crossorigin="anonymous">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% if user.is_authenticated %}
  {% for group in user.groups.all%}
    {% if group.name == "Customers" %}
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <a href="{% url 'logout' %}">Log Out</a>
        <a href="{% url 'customers:index' %}">Home</a>
        <a href="{% url 'customers:registration' %}">Register For Services</a>
        <a href="{% url 'customers:detail' user.id  %}">Customer Details</a>
        <a href="{% url 'customers:change' user.id %}">Change Your Services</a>
        <a href="{% url 'customers:pickup' user.id %}">Schedule an Extra Pickup</a>
        <a href="{% url 'customers:suspension' user.id %}">Manage Account Suspension</a>
        <a href="{% url 'customers:statement' user.id %}">View Your Statement</a>
      </div>
    </nav>
    {% elif group.name == "Employees" %}
 <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <a href="{% url 'logout' %}">Log Out</a>
        <a href="{% url 'employees:index' %}">Home</a>
        <a href="{% url 'employees:registration' %}">Register as an Employee</a>
        <a href="{% url 'employees:route' %}">Daily Route</a>

      </div>
    </nav>    {% endif %}
  {% endfor %}
{% endif %}
  <main>
    <h1>{% block header %} {% endblock %}</h1>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>
{# This is the parent template that should be extended by any other view you create #}
{# Todo: Add navbar links, link to stylesheets, style layout #}

trash_collector/templates/home.html
{% extends 'base.html' %}

{% block title %} Home Portal {% endblock %}

{% block header %} Home Portal {% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hello {{ user.username }}. You don't have a group assigned. Please contact administrator or attempt to register again.
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in. Please log in or create an account.</p>
  <a href="{% url 'login' %}">Log In</a>
  <a href="{% url 'accounts:register' %}">Sign Up</a>
{% endif %}
{% endblock %}

{# This is the home page that allows a logged out user to register or log in #}