trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('registration/', views.registration, name='registration'),
    path('route/', views.daily_view, name='route'),
    path('confirmation/', views.confirm_pickup, name='confirmation'),

]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding django's built in routes (login and logout). Notice there is no login function in accounts/views.py
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/employees/models.py
from django.db import models


# Create your models here.

# TODO: Create an Employee model with properties required by the user stories

class Employee(models.Model):
    name = models.CharField(max_length=20)
    zip_code = models.CharField(max_length=5)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    todays_customers = []

    def __str___(self):
        return self.name

trash_collector/employees/forms.py
from django.apps import apps
from django.forms import ModelForm
from .models import Employee


class NewEmployeeForm(ModelForm):
    class Meta:
        model = Employee
        fields = {"name",
                  "user",
                  "zip_code"}


class ConfirmCharge(ModelForm):
    class Meta:
        Customer = apps.get_model('customers.Customer')
        model = Customer
        fields = {"balance"}

trash_collector/employees/views.py
from datetime import date, datetime
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.apps import apps
from django.urls import reverse
from .forms import NewEmployeeForm, ConfirmCharge
from .models import Employee
# TODO: Create a function for each path created in employees/urls.py. Each will need a template as well.


def registration(request):
    form = NewEmployeeForm()
    if request.method == 'POST':
        form = NewEmployeeForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('employees:index'))
    context = {'form': form}
    return render(request, 'employees/registration.html', context)


def index(request):
    if not request.user.groups.filter(name="Employees").exists():
        return render(request, 'home.html')
    Customer = apps.get_model('customers.Customer')
    user = request.user
    try:
        employee = Employee.objects.get(user=user)
        zip_code = employee.zip_code
        today_num = date.today().weekday()
        days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
        today_day = days[today_num]
        today_date = date.today()
        customers = Customer.objects.filter(zip_code=zip_code, weekly_pickup_day=today_day)
        one_time_pickup = Customer.objects.filter(onetime_pickup=today_date, zip_code=zip_code)
        context = {
            'customers': customers, 'one_time_pickup': one_time_pickup
        }
        return render(request, 'employees/index.html', context)
    except Employee.DoesNotExist:
        return HttpResponseRedirect(reverse('employees:registration'))


def daily_view(request):
    user = request.user
    Customer = apps.get_model('customers.Customer')
    employee = Employee.objects.get(user_id=user.id)
    Customer.objects.filter(zip_code=employee.zip_code)
    route = []
    try:
        employee = Employee.objects.get(user=user)
        zip_code = employee.zip_code
        today_num = date.today().weekday()
        days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
        today_day = days[today_num]
        today_date = date.today()
        customers = Customer.objects.filter(zip_code=zip_code, weekly_pickup_day=today_day)
        one_time_pickup = Customer.objects.filter(onetime_pickup=today_date, zip_code=zip_code)
        start_date = Customer.start_suspension
        end_date = Customer.end_suspension
        if today_date.__le__(start_date) and today_date.__ge__(end_date):
            route.append(Customer)
        context = {
            'customers': customers, 'one_time_pickup': one_time_pickup, 'route': route
        }
        return render(request, 'employees/route.html', context)
    except Employee.DoesNotExist:
        return HttpResponseRedirect(reverse('employees:registration'))


def confirm_pickup(request):
    Customer = apps.get_model('customers.Customer')
    form = ConfirmCharge()
    if request.method == 'POST':
        form = ConfirmCharge()
        if form.is_valid():
            Customer.balance.save()
            return HttpResponseRedirect(reverse('employees:route'))
    context = {'form': form}
    return render(request, 'employees/confirmation.html', context)

trash_collector/employees/templates/employees/confirmation.html
{% extends 'base.html' %}

{% block title %} Change Your Services {% endblock %}

{% block header %} Change Your Services {% endblock %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button href="{% url 'employees:route' %}"  type="submit">Charge</button>
  </form>
{% endblock %}

trash_collector/employees/templates/employees/daily.html
{% extends 'base.html' %}

{% block title %} Weekly View{% endblock %}
{% block header %} <h1>Weekly View</h1> {% endblock %}
{% block content %} <p><form name='weekform' id="weekform" method="POST" action="{% url 'employees:daily' %}">
    {% csrf_token %}
      Day of Week: <select name="dayofweek" id="dayofweek">
  <option value="Monday" selected="Monday">Monday</option>
  <option value="Tuesday" selected="Tuesday">Tuesday</option>
  <option value="Wednesday" selected="Wednesday">Wednesday</option>
  <option value="Thursday" selected="Thursday">Thursday</option>
  <option value="Friday" selected="Friday">Friday</option>
  </select>
  <input type="submit" value="Submit">
</form></p>
<table>
        <tr><th>Daily Customers</th></tr>
        {% for cust in customers %}
        <tr><td>{{cust.name}}</td></tr>
        {% endfor %}
      </table>
{% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'base.html' %}

{% block title %} Daily View {% endblock %}

{% block header %} Daily View {% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hello Employee {{ user.username }}!

     <table class="table table-striped">
        <thead title="Customers">
          <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Zipcode</th>
            <th>Balance</th>
          </tr>
        </thead>
        <tbody>
        {% for cust in customers %}
          <tr>
            <td>{{ cust.name }}</td>
            <td>{{ cust.address }}</td>
            <td>{{ cust.zip_code }}</td>
            <td>${{ cust.balance }}</td>
          </tr>
        {% endfor %}
       </tbody>
      </table>
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/employees/templates/employees/register.html
{% extends 'base.html' %}

{% block title %} Register Account {% endblock %}

{% block header %} Register Account {% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
  </form>
{% endblock %}

trash_collector/employees/templates/employees/registration.html
{% extends 'base.html' %}

{% block title %} Register Account {% endblock %}

{% block header %} Register Account {% endblock %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
  </form>
{% endblock %}

trash_collector/employees/templates/employees/route.html
{% extends 'base.html' %}
{% block title %} Daily Route {% endblock %}
{% block header %} Daily Route {% endblock %}
{% block content %}



  <table class="table table-striped">
         <thead title="Customers">
          <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Zipcode</th>
            <th>Pickup Confirmation</th>
            <th>Balance</th>

          </tr>
        </thead>
        <tbody>
           {% for cus in customers %}
          <tr>
            <td>{{ cus.name }}</td>
            <td>{{ cus.address }}</td>
            <td>{{ cus.zip_code }}</td>
            <td><a href="{% url 'employees:confirmation' %}">Confirm</a></td>
            <td>{{ cus.balance }}</td>
          </tr>


           {% endfor %}
       </tbody>
      </table>
{% endblock %}